"""add project_id to documents

Revision ID: 8adf9aeed7c2
Revises: f28e1ca1c73d
Create Date: 2026-07-24 20:15:10.298115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8adf9aeed7c2'
down_revision: Union[str, Sequence[str], None] = 'f28e1ca1c73d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('project_id', sa.UUID(), nullable=False))
    op.add_column('documents', sa.Column('file_type', sa.String(length=50), nullable=False))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('storage_path', sa.String(length=500), nullable=False))
    op.add_column('documents', sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('documents', sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.create_foreign_key(None, 'documents', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('documents', 'file_path')
    op.drop_column('documents', 'content_type')
    op.drop_column('documents', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('content_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.drop_column('documents', 'uploaded_at')
    op.drop_column('documents', 'metadata_json')
    op.drop_column('documents', 'storage_path')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'file_type')
    op.drop_column('documents', 'project_id')
    # ### end Alembic commands ###
