"""link chats to projects

Revision ID: 9e3557229743
Revises: 59a51d3be316
Create Date: 2026-07-24 13:14:13.283641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e3557229743'
down_revision: Union[str, Sequence[str], None] = '59a51d3be316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('project_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'chats', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'project_id')
    # ### end Alembic commands ###
